### ISSUE TITLE
fatal error when running npm start

### ISSUE THREAD

**Issue by bcherny** [turrisjs/generator-turris#42] opened 2015-12-06 19:47 UTC
``` sh
> gulp

/Users/boris/Sites/foo/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/boris/Sites/foo/client/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)

npm ERR! Darwin 14.5.0
npm ERR! argv "/Users/boris/.nvm/v4.2.2/bin/node" "/Users/boris/.nvm/v4.2.2/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v3.5.1
npm ERR! code ELIFECYCLE
npm ERR! foo@1.0.0 start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the foo@1.0.0 start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the foo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs foo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls foo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/boris/Sites/foo/client/npm-debug.log
```

**Comment by yamalight** [comment] 2015-12-07 09:38
@bcherny just re-scaffolded the fresh project and it worked just fine - I cannot reproduce this issue. can you give more details on steps you took?

**Comment by dougajmcdonald** [comment] 2016-01-21 15:55
I'm seeing this issue on a totally unrelated project, so I believe it's a corruption of babel-core installation maybe?

**Comment by yamalight** [comment] 2016-01-21 16:31
@dougajmcdonald it seems so.
couldn't reproduce this issue at all and there's been no feedback, so I'm just going to close it.

**Closed as completed by yamalight** 2016-01-21 16:31 UTC
